@startuml
actor User
actor Admin

User -- (Register)
User -- (Login)
User -- (Upload File)
User -- (Download File)
User -- (Mark File as Favorite)

Admin -- (Manage Subjects)
Admin -- (Delete File)
Admin -- (View All Users)

User -- (View Subjects)
User -- (View Files)

@enduml 